# Generated by Django 3.2.7 on 2021-10-02 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task1',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='create',
            new_name='created',
        ),
    ]
