# Generated by Django 3.2.7 on 2021-10-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_auto_20211002_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
